# This is a generated file. Not intended for manual editing.
services:
  telemetry.api:
    build:
      context: "/Users/dosymep/RiderProjects/Bim4EveryoneTelemetry/src/Bim4EveryoneTelemetry"
      dockerfile: "Dockerfile"
      target: "sdk"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Bim4EveryoneTelemetry.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "bim4everyonetelemetry:dev"
    ports: []
    volumes:
    - "/Users/dosymep/.microsoft/usersecrets:/root/.microsoft/usersecrets"
    - "/Users/dosymep/.nuget/packages:/root/.nuget/packages"
    - "/Users/dosymep/RiderProjects/Bim4EveryoneTelemetry/src/Bim4EveryoneTelemetry:/app:rw"
    - "/Users/dosymep/RiderProjects/Bim4EveryoneTelemetry:/src:rw"
    working_dir: "/app"
