services:
  telemetry.db:
    container_name: telemetry-db
    image: mongo
    command: --auth
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: Bim4Everyone
    volumes:
      - ./mongodb:/data/db
  
  telemetry.api:
    container_name: telemetry-api
    depends_on:
      - telemetry.db
    build: ./src/Bim4EveryoneTelemetry/
    ports:
      - 80:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development